### ISSUE TITLE
missing forward function ?

### ISSUE THREAD

**Issue by Neuronys** [sobamchan/pytorch-lightning-transformers#1]
Hi @sobamchan 
Thanks for the Medium article and sample code.
However, it seems outdated with the latest version of Pytorch-Lightning.
I got this error
`TypeError: Can't instantiate abstract class Model with abstract methods forward`

Apparently, the latest version requires the forward function.
What would you put in it ?

Thanks in advance for your advice
Philippe

**Comment by sobamchan** [comment]
@Neuronys 
Thanks for your report!

I haven't updated any deps in this project actually.
I will look into it, and hopefully, get back to you before this weekend finishes:)

or

You can simply refer the `Pipfile.lock` file to see which pytorch-lighting version this project was working with.

**Comment by Neuronys** [comment]
@sobamchan 
I add this and it seems to work :-)

**_def forward(self, x):
      return self.model(x)_**

**Comment by sobamchan** [comment]
@Neuronys 
Cool!

I will try to update the version sometime soon.
(Or you can probably send a PR :))
